"""Premium runs out -> free (task.md; decided with the user 2026-10-03: Tibiantis' rules). Tibiantis FAQ: "Houses are
lost during the next server save, character is moved out of premium area upon the next login, promotion is
deactivated [...] The selected premium outfit can still be used until it is changed."

creaturescripts/scripts/login.lua (premiumExpired), creaturescripts/lib/premium_areas.lua (generated by
tools/premium-areas.py from the map, tibia74/premium.py), protocolgame.cpp parseSetOutfit (the outfit). The promotion
is test_death.py's, the house (lost at the server save) test_server_save.py's."""
import time
from pathlib import Path

import pytest

from tibia74 import GameClient, SERVER_DIR
from tibia74.net import Writer
from tibia74.otbm import read_towns

TOWNS = {t.name: t for t in read_towns(SERVER_DIR / "data" / "world" / "Tibia74.otbm")}
THAIS, EDRON, CARLIN, ROOKGAARD = (TOWNS[n] for n in ("Thais", "Edron", "Carlin", "Rookgaard"))
DARASHIA, ANKRAHMUN, VENORE = TOWNS["Darashia"].temple, TOWNS["Ankrahmun"].temple, TOWNS["Venore"].temple
ROOK_PREMIUM_SIDE = (32035, 32185, 6)       # in front of the Gatekeeper, past King's Bridge
THAIS_ROAD = (32369, 32245, 7)              # just south of the Thais temple
MOVED = "You have been moved out of the premium area."
BEGINNER_SET = {30001: 1}


def _login_as(server, items, character):
    c = GameClient(items, port=server.port)
    c.login(character.account, character.password, character.name)
    c.character = character
    return c


# ---------------------------------------------------------------------------------------------- premium areas

def test_premium_areas_match_the_map(world_map):
    """premium_areas.lua is what the map says: every tile you can only reach through a premium ship, carpet or King's
    Bridge is in a box, no tile you can walk to from a free town is (rerun tools/premium-areas.py after a map change)."""
    from tibia74.premium import areas, read_lua_boxes
    boxes = read_lua_boxes(SERVER_DIR / "data" / "creaturescripts" / "lib" / "premium_areas.lua")
    assert boxes, "premium_areas.lua has no boxes"

    def area_of(p):
        return next((name for lo, hi, name in boxes if all(lo[i] <= p[i] <= hi[i] for i in range(3))), None)

    free, premium = areas(world_map, SERVER_DIR)
    wrong_free = [p for p in free if area_of(p)]
    assert not wrong_free, f"{len(wrong_free)} free tiles inside a premium box, e.g. {wrong_free[:5]}"
    for name, tiles in premium.items():
        missing = [p for p in tiles if area_of(p) != name]
        assert not missing, f"{len(missing)} {name} premium tiles outside its boxes, e.g. {missing[:5]}"
    for town in ("Edron", "Darashia", "Ankrahmun"):
        assert area_of(TOWNS[town].temple) == "mainland", town
    for town in ("Thais", "Carlin", "Kazordoon", "Ab'Dendriel", "Venore", "Fibula", "Rookgaard"):
        assert area_of(TOWNS[town].temple) is None, town
    assert area_of(ROOK_PREMIUM_SIDE) == "rookgaard"


# ---------------------------------------------------------------------------------------------- moved out

@pytest.mark.parametrize("where", [EDRON.temple, DARASHIA, ANKRAHMUN], ids=["Edron", "Darashia", "Ankrahmun"])
def test_a_free_character_in_a_premium_area_logs_in_at_the_thais_temple(new_player, where):
    p = new_player(pos=where, premium_days=0, town_id=CARLIN.id, storage=BEGINNER_SET)
    assert p.wait_for(lambda: p.pos == THAIS.temple, timeout=5), f"logged in at {p.pos}, not the Thais temple"
    assert p.wait_for(lambda: p.messages(MOVED), timeout=3), p.text_messages[-3:]


def test_a_premium_character_stays_in_the_premium_area(new_player, db):
    p = new_player(pos=EDRON.temple, premium_days=30, town_id=EDRON.id, storage=BEGINNER_SET)
    time.sleep(1)
    assert p.pos == EDRON.temple, p.pos
    assert not p.messages(MOVED)
    guid = p.character.guid
    p.logout()
    assert db.town_after_logout(guid, EDRON.id, timeout=10) == EDRON.id


def test_a_free_character_on_free_ground_stays_and_keeps_its_home_town(new_player, db):
    p = new_player(pos=VENORE, premium_days=0, town_id=CARLIN.id, storage=BEGINNER_SET)
    time.sleep(1)
    assert p.pos == VENORE, p.pos
    assert not p.messages(MOVED)
    guid = p.character.guid
    p.logout()
    assert db.town_after_logout(guid, CARLIN.id, timeout=10) == CARLIN.id


@pytest.mark.parametrize("where", [EDRON.temple, VENORE], ids=["in Edron", "in Venore"])
def test_a_free_citizen_of_a_premium_town_becomes_a_citizen_of_thais(new_player, db, where):
    """Else it would respawn in Edron after a death (TibiaWiki "Premium Time": "at the temple of Thais (if they are a
    citizen of a premium city or Thais)")."""
    p = new_player(pos=where, premium_days=0, town_id=EDRON.id, storage=BEGINNER_SET)
    time.sleep(1)
    guid = p.character.guid
    p.logout()
    assert db.town_after_logout(guid, THAIS.id, timeout=10) == THAIS.id


def test_the_rookgaard_premium_side_sends_to_the_rookgaard_temple(new_player, db):
    """A Rookgaard character does not leave the island that way."""
    p = new_player(pos=ROOK_PREMIUM_SIDE, premium_days=0, town_id=ROOKGAARD.id, storage=BEGINNER_SET)
    assert p.wait_for(lambda: p.pos == ROOKGAARD.temple, timeout=5), f"logged in at {p.pos}"
    assert p.messages(MOVED)
    guid = p.character.guid
    p.logout()
    assert db.town_after_logout(guid, ROOKGAARD.id, timeout=10) == ROOKGAARD.id


# ---------------------------------------------------------------------------------------------- the house

HOUSE_NAME, HOUSE_TILE = "Castle Shop 2", (33208, 31798, 7)    # house 474, Edron (Tibia74-houses.xml, townid 6)


def _house_of(gm, name):
    start = len(gm.text_messages)
    gm.say(f"/gethouse {name}")
    assert gm.wait_for(lambda: any(name in t and "house" in t for _, t in gm.text_messages[start:]), timeout=3)
    return next(t for _, t in gm.text_messages[start:] if name in t and "house" in t)


@pytest.mark.parametrize("premium_days", [0, 30], ids=["free", "premium"])
def test_the_house_is_kept_at_login(new_player, db, server, items, premium_days):
    """Tibiantis FAQ: "Houses are lost during the next server save" - not at the login. The release (items to the
    depot of the house's town) is test_server_save.py's."""
    owner = db.create_character(pos=THAIS_ROAD, premium_days=premium_days, town_id=THAIS.id, storage=BEGINNER_SET)
    gm = new_player(pos=HOUSE_TILE, group_id=3, storage=BEGINNER_SET)
    gm.say(f"/owner {owner.name}")
    assert gm.wait_for(lambda: HOUSE_NAME in _house_of(gm, owner.name), timeout=5)
    p = _login_as(server, items, owner)
    try:
        time.sleep(1)
        assert not p.messages("lost your house")
        assert HOUSE_NAME in _house_of(gm, owner.name)
    finally:
        p.logout()
    # free the house again for the other tests of the session (/owner kicked the first GM out of it)
    gm2 = new_player(pos=HOUSE_TILE, group_id=3, storage=BEGINNER_SET)
    gm2.say("/owner none")
    assert gm2.wait_for(lambda: "does not own any house" in _house_of(gm2, owner.name), timeout=5)


# ---------------------------------------------------------------------------------------------- the outfit

NOBLEMAN, SUMMONER, HUNTER = 132, 133, 129     # male: 128-131 free, 132-134 premium (protocolgame.cpp)


def _with_outfit(new_player, db, server, items, looktype, premium_days=0):
    """A character that logs in wearing `looktype` (the one it chose while it had premium)."""
    p = new_player(pos=THAIS_ROAD, premium_days=30, storage=BEGINNER_SET)
    character = p.character
    p.logout()
    con = db._connect()
    con.execute("UPDATE players SET looktype = ?, lookhead = 1, lookbody = 2, looklegs = 3, lookfeet = 4 WHERE id = ?",
                (looktype, character.guid))
    con.execute("UPDATE accounts SET premend = ? WHERE id = ?",
                (int(time.time()) + premium_days * 86400 if premium_days else 0, character.account))
    con.commit()
    con.close()
    time.sleep(1)
    return _login_as(server, items, character)


def _outfit(c):
    return c.wait_for(lambda: c.creatures.get(c.player_id), timeout=5).outfit


def _set_outfit(c, looktype, colours=(10, 20, 30, 40)):
    c._send(Writer().u8(0xD3).u8(looktype).u8(colours[0]).u8(colours[1]).u8(colours[2]).u8(colours[3]))
    time.sleep(1)


def test_the_premium_outfit_is_kept_at_login(new_player, db, server, items):
    p = _with_outfit(new_player, db, server, items, NOBLEMAN)
    try:
        assert _outfit(p) == (NOBLEMAN, 1, 2, 3, 4)
    finally:
        p.logout()


def test_the_kept_premium_outfit_can_get_new_colours(new_player, db, server, items):
    """Needs the protocolgame.cpp change (rebuild): the old server turned the character invisible (look type 0)."""
    p = _with_outfit(new_player, db, server, items, NOBLEMAN)
    try:
        _set_outfit(p, NOBLEMAN)
        assert _outfit(p) == (NOBLEMAN, 10, 20, 30, 40)
    finally:
        p.logout()


def test_another_premium_outfit_is_refused(new_player, db, server, items):
    """Needs the protocolgame.cpp change (rebuild)."""
    p = _with_outfit(new_player, db, server, items, NOBLEMAN)
    try:
        _set_outfit(p, SUMMONER)
        assert _outfit(p) == (NOBLEMAN, 1, 2, 3, 4)
    finally:
        p.logout()


def test_once_changed_the_premium_outfit_is_gone(new_player, db, server, items):
    """Needs the protocolgame.cpp change (rebuild)."""
    p = _with_outfit(new_player, db, server, items, NOBLEMAN)
    try:
        _set_outfit(p, HUNTER)
        assert _outfit(p)[0] == HUNTER
        _set_outfit(p, NOBLEMAN)
        assert _outfit(p)[0] == HUNTER
    finally:
        p.logout()


def test_a_premium_character_may_pick_any_premium_outfit(new_player, db, server, items):
    p = _with_outfit(new_player, db, server, items, NOBLEMAN, premium_days=30)
    try:
        _set_outfit(p, SUMMONER)
        assert _outfit(p) == (SUMMONER, 10, 20, 30, 40)
    finally:
        p.logout()
