"""Compares every NPC's shop with docs/reference-74/npc-shops.json (tools/wiki-npc-reference.py) and writes
docs/reference-74/npc-shops.md: per NPC the wares whose price differs, the wiki's wares we lack, and ours the wiki
does not list. A guide for the shop audit, not a verdict: the wiki's early lists were partly copied between NPCs
(Al Dee's 2005 list lacks his own pick) and carry typos (Rachel's mana fluid "5 gp").

    python tools/compare-npc-shops.py
"""
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))
from tibia74 import SERVER_DIR                      # noqa: E402
from tibia74.npcs import load_npcs                  # noqa: E402

REF = ROOT / "docs" / "reference-74" / "npc-shops.json"
OUT = ROOT / "docs" / "reference-74" / "npc-shops.md"


def norm(name):
    name = name.lower().strip()
    name = re.sub(r"^(an?|the) ", "", name)
    name = re.sub(r"^(vial|flask|mug) of ", "", name)
    name = re.sub(r" kit$", "", name)                # furniture is sold as a kit
    name = name.replace("cusioned", "cushioned")
    return re.sub(r"[^a-z' ]", "", name).strip()


def item_names():
    names = {}
    for item in ET.parse(SERVER_DIR / "data" / "items" / "items.xml").getroot():
        name = item.get("name")
        if not name:
            continue
        ids = [int(item.get("id"))] if item.get("id") else range(int(item.get("fromid")), int(item.get("toid")) + 1)
        for i in ids:
            names[i] = norm(name)
    return names


def ours(shop, items):
    """{normalized name: price} - by the NPC's own word for it and by the item's name."""
    out = {}
    for ware in shop:
        for key in {norm(ware.real_name or ware.names[0]), items.get(ware.item_id, "")} - {""}:
            out.setdefault(key, ware.price)
    return out


def diff(theirs, mine):
    """(price differences, the wiki's wares we lack, ours the wiki lacks)"""
    theirs = {norm(k): v for k, v in theirs.items()}
    differ = [(k, mine[k], v) for k, v in sorted(theirs.items()) if k in mine and mine[k] != v]
    missing = [(k, v) for k, v in sorted(theirs.items()) if k not in mine]
    matched = set(theirs) & set(mine)
    return differ, missing, matched


def main():
    ref = json.loads(REF.read_text(encoding="utf-8"))
    items = item_names()
    npcs = load_npcs(SERVER_DIR)
    lines = ["# NPC shops against TibiaWiki", "",
             "Generated by `tools/compare-npc-shops.py` from `npc-shops.json` (`tools/wiki-npc-reference.py`: each NPC's",
             "earliest TibiaWiki revision with a ware list, before 8.0). \"sells\" = what the player buys from the NPC.",
             "A guide, not a verdict - the early wiki lists were partly copied between NPCs and have typos.", ""]
    clean, nolist = [], []
    for name in sorted(ref):
        entry, npc = ref[name], npcs.get(name)
        if not entry or npc is None:
            continue
        if not entry["sells"] and not entry["buys"]:
            if npc.buyable or npc.sellable:
                nolist.append(name)
            continue
        out = []
        for side, theirs, shop in (("sells", entry["sells"], npc.buyable), ("buys", entry["buys"], npc.sellable)):
            mine = ours(shop, items)
            differ, missing, matched = diff(theirs, mine)
            ours_keys = {norm(w.real_name or w.names[0]): w for w in shop}
            extra = sorted(k for k, w in ours_keys.items()
                           if k not in matched and items.get(w.item_id, "") not in matched)
            if differ:
                out.append(f"- {side} at another price: " + ", ".join(f"{k} {a} (wiki {b})" for k, a, b in differ))
            if missing:
                out.append(f"- {side} on the wiki, not ours: " + ", ".join(f"{k} {v}" for k, v in missing))
            if extra and theirs:
                out.append(f"- {side} ours, not on the wiki: " + ", ".join(extra))
        if out:
            lines += [f"## {name}", "", f"TibiaWiki rev {entry['rev']} ({entry['date']})", ""] + out + [""]
        else:
            clean.append(name)
    lines += ["## Matching the wiki", "", ", ".join(clean) or "-", "",
              "## A shop of ours, no ware list on the wiki before 8.0", "", ", ".join(nolist) or "-", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT}: {sum(1 for l in lines if l.startswith('## ')) - 2} NPCs differ, {len(clean)} match, "
          f"{len(nolist)} without a list")


if __name__ == "__main__":
    main()
