r"""Write server/data/creaturescripts/lib/premium_areas.lua: the premium areas of the map as boxes, worked out from
the map (tests/tibia74/premium.py says how). Run it again after a map change that opens or closes a way into a
premium area; tests/test_premium_expiry.py::test_premium_areas_match_the_map fails until then.

    tests\.venv\Scripts\python tools\premium-areas.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from tibia74 import SERVER_DIR  # noqa: E402
from tibia74.premium import areas, cover  # noqa: E402
from tibia74.worldmap import WorldMap  # noqa: E402

OUT = SERVER_DIR / "data" / "creaturescripts" / "lib" / "premium_areas.lua"

HEADER = """\
-- Premium areas: where a character whose premium ran out may not log in (creaturescripts/scripts/login.lua).
-- GENERATED by tools/premium-areas.py from the map - do not edit by hand; tests/test_premium_expiry.py checks it.
-- The map has no premium tile flag; what it marks is the way in (premium-only ships and carpets, King's Bridge on
-- Rookgaard, action id 50003). A premium area is what you can only reach that way: "mainland" = Edron, Cormaya,
-- Stonehome, Eremo's island, Darashia, Ankrahmun, Drefia, the djinn fortresses, the Ghost Ship; "rookgaard" = the
-- Rookgaard premium side. Each box holds premium tiles and no free one ({x1, y1, z1, x2, y2, z2, area}).
"""

FOOTER = """
function getPremiumArea(pos)
	for _, b in ipairs(PREMIUM_AREAS) do
		if pos.x >= b[1] and pos.y >= b[2] and pos.z >= b[3] and pos.x <= b[4] and pos.y <= b[5] and pos.z <= b[6] then
			return b[7]
		end
	end
	return nil
end
"""


def main():
    world = WorldMap.load(SERVER_DIR, ROOT / "tests" / ".run")
    free, premium = areas(world, SERVER_DIR)
    lines = [HEADER, "PREMIUM_AREAS = {"]
    for name, tiles in premium.items():
        boxes = sorted(cover(tiles, free))
        print(f"{name}: {len(tiles)} tiles, {len(boxes)} boxes")
        for (x1, y1, z1), (x2, y2, z2) in boxes:
            lines.append(f'\t{{{x1}, {y1}, {z1}, {x2}, {y2}, {z2}, "{name}"}},')
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n" + FOOTER, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
