-- Premium areas: where a character whose premium ran out may not log in (creaturescripts/scripts/login.lua).
-- GENERATED by tools/premium-areas.py from the map - do not edit by hand; tests/test_premium_expiry.py checks it.
-- The map has no premium tile flag; what it marks is the way in (premium-only ships and carpets, King's Bridge on
-- Rookgaard, action id 50003). A premium area is what you can only reach that way: "mainland" = Edron, Cormaya,
-- Stonehome, Eremo's island, Darashia, Ankrahmun, Drefia, the djinn fortresses, the Ghost Ship; "rookgaard" = the
-- Rookgaard premium side. Each box holds premium tiles and no free one ({x1, y1, z1, x2, y2, z2, area}).

PREMIUM_AREAS = {
	{32946, 32332, 0, 33060, 32915, 15, "mainland"},
	{33044, 31586, 0, 33208, 31923, 15, "mainland"},
	{33061, 32257, 0, 33403, 32914, 15, "mainland"},
	{33209, 31588, 0, 33373, 32185, 15, "mainland"},
	{31938, 32206, 10, 32027, 32254, 10, "rookgaard"},
	{31944, 32204, 8, 31991, 32252, 9, "rookgaard"},
	{31968, 32187, 8, 31988, 32203, 8, "rookgaard"},
	{31968, 32194, 11, 32026, 32252, 13, "rookgaard"},
	{31972, 32194, 10, 32060, 32205, 10, "rookgaard"},
	{31973, 32191, 0, 31978, 32198, 15, "rookgaard"},
	{31974, 32213, 0, 31990, 32234, 15, "rookgaard"},
	{31975, 32199, 6, 32041, 32212, 7, "rookgaard"},
	{31979, 32189, 6, 31982, 32198, 7, "rookgaard"},
	{31983, 32187, 6, 31993, 32198, 7, "rookgaard"},
	{31991, 32213, 0, 32003, 32244, 15, "rookgaard"},
	{31992, 32204, 0, 32013, 32254, 15, "rookgaard"},
	{31997, 32151, 8, 32026, 32203, 9, "rookgaard"},
	{31998, 32189, 10, 32031, 32193, 10, "rookgaard"},
	{32004, 32190, 0, 32013, 32198, 15, "rookgaard"},
	{32004, 32213, 0, 32012, 32241, 15, "rookgaard"},
	{32009, 32166, 10, 32030, 32188, 10, "rookgaard"},
	{32009, 32181, 7, 32014, 32189, 7, "rookgaard"},
	{32013, 32213, 0, 32019, 32249, 15, "rookgaard"},
	{32014, 32190, 0, 32020, 32198, 15, "rookgaard"},
	{32014, 32247, 0, 32021, 32255, 15, "rookgaard"},
	{32015, 32185, 0, 32016, 32189, 15, "rookgaard"},
	{32017, 32185, 0, 32032, 32189, 15, "rookgaard"},
	{32020, 32213, 7, 32024, 32250, 7, "rookgaard"},
	{32024, 32190, 0, 32028, 32198, 15, "rookgaard"},
	{32025, 32216, 6, 32025, 32250, 7, "rookgaard"},
	{32026, 32215, 6, 32026, 32250, 7, "rookgaard"},
	{32027, 32151, 8, 32029, 32199, 8, "rookgaard"},
	{32027, 32170, 9, 32038, 32214, 9, "rookgaard"},
	{32027, 32215, 6, 32027, 32250, 7, "rookgaard"},
	{32028, 32206, 10, 32040, 32217, 10, "rookgaard"},
	{32028, 32213, 7, 32028, 32232, 7, "rookgaard"},
	{32028, 32243, 0, 32028, 32250, 15, "rookgaard"},
	{32029, 32190, 0, 32032, 32198, 15, "rookgaard"},
	{32029, 32213, 7, 32030, 32232, 7, "rookgaard"},
	{32029, 32241, 6, 32032, 32251, 7, "rookgaard"},
	{32030, 32152, 8, 32036, 32176, 8, "rookgaard"},
	{32031, 32213, 7, 32034, 32221, 7, "rookgaard"},
	{32033, 32182, 6, 32037, 32189, 7, "rookgaard"},
	{32033, 32190, 0, 32035, 32198, 15, "rookgaard"},
	{32033, 32242, 6, 32036, 32252, 7, "rookgaard"},
	{32035, 32213, 7, 32039, 32213, 7, "rookgaard"},
	{32036, 32192, 0, 32039, 32198, 15, "rookgaard"},
	{32037, 32247, 7, 32039, 32250, 7, "rookgaard"},
	{32039, 32168, 9, 32044, 32214, 9, "rookgaard"},
	{32040, 32190, 7, 32043, 32198, 7, "rookgaard"},
	{32044, 32183, 6, 32054, 32189, 7, "rookgaard"},
	{32044, 32190, 6, 32056, 32196, 7, "rookgaard"},
	{32045, 32187, 8, 32046, 32198, 9, "rookgaard"},
	{32047, 32186, 8, 32051, 32197, 9, "rookgaard"},
	{32052, 32185, 8, 32064, 32203, 9, "rookgaard"},
	{32054, 32206, 10, 32057, 32207, 10, "rookgaard"},
	{32057, 32189, 10, 32093, 32193, 10, "rookgaard"},
	{32060, 32166, 10, 32096, 32188, 11, "rookgaard"},
	{32065, 32185, 8, 32066, 32196, 9, "rookgaard"},
	{32067, 32184, 8, 32070, 32188, 9, "rookgaard"},
}

function getPremiumArea(pos)
	for _, b in ipairs(PREMIUM_AREAS) do
		if pos.x >= b[1] and pos.y >= b[2] and pos.z >= b[3] and pos.x <= b[4] and pos.y <= b[5] and pos.z <= b[6] then
			return b[7]
		end
	end
	return nil
end
